# Generated by Django 3.2.7 on 2021-10-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='/static/default.png', upload_to='static/profile_pics/'),
        ),
    ]
