# Generated by Django 3.2.7 on 2021-10-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='https://bibliotecapictures.s3.amazonaws.com/media/profile_pics/'),
        ),
    ]
