# Generated by Django 3.2.7 on 2021-10-26 05:12

import biblioteca.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='default.png', storage=biblioteca.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
