# Generated by Django 3.2.7 on 2021-10-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_publicacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(default='/static/default.png', upload_to='static/publicaciones/'),
        ),
    ]
