# Generated by Django 3.2.7 on 2021-10-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_historicalautor_historicalejemplar_historicalgenero_historicalidioma_historicalpublicacion_historica'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalautor',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalejemplar',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgenero',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalidioma',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpublicacion',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltipo',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address'),
            preserve_default=False,
        ),
    ]
