# Generated by Django 3.2.7 on 2021-10-08 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20211007_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalEjemplar',
        ),
    ]
