# Generated by Django 3.2.7 on 2021-10-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_historicalejemplar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['fecha_vencimiento'], 'permissions': (('puede_marcar_devolucion', 'Marcar ejemplar devuelto'),), 'verbose_name': 'Ejemplar', 'verbose_name_plural': 'Ejemplares'},
        ),
    ]
