# Generated by Django 3.2.7 on 2021-10-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_auto_20211023_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(default='/static/default.png', upload_to='publicaciones/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(default='/static/default.png', upload_to='publicaciones/'),
        ),
    ]
