# Generated by Django 3.2.7 on 2021-10-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_auto_20211024_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpublicacion',
            name='imagen',
            field=models.TextField(default='default.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(default='default.png', upload_to='publicaciones/'),
        ),
    ]
