# Generated by Django 3.2.7 on 2021-10-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_auto_20211025_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['fecha_vencimiento'], 'permissions': (('puede_marcar_devolucion', 'Aplicar devolucion de Ejemplar'), ('puede_aprobar_prestamos', 'Aprobar prestamos'), ('puede_solicitar_prestamos', 'Solicitar prestamos'), ('puede_ver_prestamos', 'Ver todos los prestamos')), 'verbose_name': 'Ejemplar', 'verbose_name_plural': 'Ejemplares'},
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalejemplar',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
